import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-context";

import { Toaster } from 'sonner';
import ErrorBoundary from "@/components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ErrorBoundary>
            {children}
            <Toaster />
          </ErrorBoundary>
        </AuthProvider>

        <script dangerouslySetInnerHTML={{
          __html: `
            window.addEventListener('unhandledrejection', (event) => {
              console.error('Unhandled Promise Rejection:', event.reason);
            });
            window.addEventListener('error', (event) => {
              console.error('Global Error Captured:', event.error || event.message);
            });
          `
        }} />
      </body>
    </html>
  );
}
